osx_image: xcode9.3
language: swift
xcode_project: sample-ci-project.xcodeproj
xcode_scheme: sample-ci-project

before_install:
  - gem update fastlane --no-ri --no-rdoc --no-document

script: fastlane test

git:
  depth: 1