os: osx
osx_image: xcode9.3
language: swift
xcode_project: sample-ci-project.xcodeproj
xcode_scheme: sample-ci-project

script: xcodebuild -showBuildSettings -scheme sample-ci-project -project ./sample-ci-project.xcodeproj

git:
  depth: 1