osx_image: xcode11.3
language: swift
xcode_project: sample-ci-project.xcodeproj
xcode_scheme: sample-ci-project

before_install:
  - chmod +x ./scripts/install_swiftlint.sh
  - ./scripts/install_swiftlint.sh
  - chmod +x ./scripts/update_fastlane.sh
  - ./scripts/update_fastlane.sh

script: 
  - swiftlint lint --config ./configs/swiftlint.yml --strict
  - bundle exec fastlane test

notifications:
  email:
    recipients:
      - celpand@gmail.com
    on_success: always
    on_failure: always

git:
  depth: 1
