name: Branch push CI

on: push

# Documentation with macOS virtual environment: 
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      xcode: ['/Applications/Xcode_11.3.app/Contents/Developer']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bundle install
        run: bundle install

      - name: Build and test
        run: bundle exec fastlane test
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}

  code_cov:
    name: Upload to codecov.io
    needs: build_and_test

    steps:
      - name: Upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
