name: Branch push CI

# Documentation with macOS virtual environment: 
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bundle install
        run: bundle install

      - name: Build and test
        run: bundle exec fastlane test

  code_cov:
    name: Upload to codecov.io
    runs-on: macos-latest
    needs: build_and_test

    steps:
      - name: Upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
