name: Branch push CI

# Documentation with macOS virtual environment: 
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:
  test:
    name: Test and codecov upload
    runs-on: macos-latest

    strategy:
      matrix:
        destination: ["name=iPhone 11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Swiftlint
        run: |
          chmod +x ./scripts/install_swiftlint.sh
          ./scripts/install_swiftlint.sh
          swiftlint lint --config ./configs/swiftlint.yml --strict

      - name: Test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "sample-ci-project" -project "sample-ci-project.xcodeproj" -destination "${{ matrix.destination }}" -enableCodeCoverage YES clean test | xcpretty

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
