name: Branch push CI

# Documentation with macOS virtual environment: 
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:
  test:
    name: Test and upload codecov
    runs-on: macos-latest

    strategy:
      matrix:
        destination: ["name=iPhone 11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "sample-ci-project" -project "sample-ci-project.xcodeproj" -destination "${{ matrix.destination }}" -enableCodeCoverage YES clean test | xcpretty

      - name: Upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
